### ISSUE TITLE
TypeError during setup

### ISSUE THREAD

**Issue by dGilli** [denoland/saaskit#167] opened 2023-05-08 07:16 UTC
I receive the following shell error just after following the setup steps then running `deno task start`:

```
Task start deno run --unstable -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 22 routes and 1 islands.
error: Uncaught TypeError: parser error: expected token Close, found '{' of type Open
        pattern: new URLPattern({ pathname: path }),
                 ^
    at new URLPattern (ext:deno_url/01_urlpattern.js:65:28)
    at buildInternalRoutes (https://deno.land/x/rutt@0.1.0/mod.ts:223:18)
    at Module.router (https://deno.land/x/rutt@0.1.0/mod.ts:275:7)
    at ServerContext.handler (https://deno.land/x/fresh@1.1.5/src/server/context.ts:313:24)
    at start (https://deno.land/x/fresh@1.1.5/src/server/mod.ts:70:21)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async file:///Users/xxx/Projects/saaskit/main.ts:14:1
Watcher Process finished. Restarting on file change...
```

- OS: macOS 12.2
- Browser: n/a
- Version: n/a

`deno --version`:

- deno 1.33.2 (release, aarch64-apple-darwin)
- v8 11.4.183.1
- typescript 5.0.3

I tried a clean install of deno and cleared my cache completely. We had one person in Discord report the same issue and another that could not reproduce.

**Comment by iuioiua** [comment] 2023-05-09 00:03
Hi @dGilli, is this a Docker container you're trying to set up? If so, the action you've completed is already outlined at the end of the [Setting Up Docker section](https://github.com/denoland/saaskit#setting-up-docker).

**Comment by ajile-in** [comment] 2023-05-09 15:12
> 

I did the same thing, and it worked for me as well. BTW, I am not using Docker.

**Comment by iuioiua** [comment] 2023-05-10 06:48
Do you experience any issues when setting up a [basic Fresh demo app](https://fresh.deno.dev/#getting-started)?

**Comment by iuioiua** [comment] 2023-05-14 09:44
I believe the issue is that `.example.env` contains the `DENO_DEPLOYMENT_ID` environmental variable. This variable is not necessary for local development. The above PR aims to fix that by simply removing that variable. Instructions to add this environmental variable later in the guide.

For those having this issue, please remove the `DENO_DEPLOYMENT_ID` environmental variable from your `.env` if developing locally. Can you please confirm if this fixes the issue?

**Comment by iuioiua** [comment] 2023-05-14 09:51
I'll wait to hear if the issue is resolved before closing.

**Comment by ajile-in** [comment] 2023-05-14 20:05
> I'll wait to hear if the issue is resolved before closing.

It works when you delete the DENO_DEPLOYMENT_ID from .env, as now it is not needed.

**Comment by iuioiua** [comment] 2023-05-14 20:40
Good enough for me. To the others, let me know if you have any issues. Closing this issue now.

**Closed by iuioiua** 2023-05-14 20:41 UTC
Labels: bug
