### ISSUE TITLE
Incorrect email in Stripe checkout

### ISSUE THREAD

**Issue by umaar** [denoland/saaskit#83] opened 2023-04-13 00:46 UTC
Hey, I assume there's some code in this repo that helps pre-fill the Stripe email. If I sign up to saaskit with a new user, I see the Stripe email is of a previous/old user:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/381495/231616944-60091ca4-da70-4d3e-ae9a-2c28a8841b03.png">

**Comment by umaar** [comment] 2023-04-13 00:48
Hold up, I disabled RLS because of https://github.com/denoland/saaskit/issues/78 - just for testing, I guess that's why I'm seeing this behaviour!

**Comment by iuioiua** [comment] 2023-04-14 03:21
@umaar, are you still seeing this issue?

**Comment by umaar** [comment] 2023-04-14 17:01
Haven't tried it again, but feel free to close if you can't repro!

**Comment by iuioiua** [comment] 2023-04-15 01:05
I could not reproduce this issue on my local machine or the online demo app. I'll close this issue for now, but if you reencounter it, please feel free to re-open it.

**Closed by iuioiua** 2023-04-15 01:05 UTC
Labels: bug
