### ISSUE TITLE
Documentation update request: Supabase setup

### ISSUE THREAD

**Issue by matthew-dean** [denoland/saaskit#58] opened 2023-04-10 04:25 UTC
In the root README.md, it has steps to do in Supabase, and it seems like those changes happen in two different dashboards. There's a local server (is it a local instance of Supabase?) at `http://localhost:54323` with a Supabase dashboard, and I guess there's a dashboard representing the Supabase account we just set up.

The documentation is very vague about which thing to do where. It suggests that tables are set up in the local dashboard, but then goes on to describe steps that presumably can only happen in `app.supabase.com` because that's the only place where those menu items exist (like for authentication).

Can you please say which steps to do locally, and which steps to do remotely, since they are two very similar dashboards?

**Comment by lambtron** [comment] 2023-04-17 19:36
hey matt,

we updated the documentation to better reflect setting up supabase to run saaskit locally. i went through this process and even created a video: https://www.youtube.com/watch?v=1GYs3NbVCfE

do you mind trying again with the new documentation? if it suits what you're looking for, then we can close the comment.

thanks for your feedback and let us know if there is anything else. our goal is to make this project as easy to use as possible!

**Comment by matthew-dean** [comment] 2023-04-17 23:47
@lambtron Thanks so much, I will give it a shot!

**Comment by iuioiua** [comment] 2023-04-24 00:40
Hi @matthew-dean, how did you go with the documentation?

**Comment by iuioiua** [comment] 2023-05-03 06:21
Hi @matthew-dean, I'll go ahead and close this issue. If you think the issue isn't solved, you can re-open it 😄

**Closed by iuioiua** 2023-05-03 06:21 UTC
Labels: enhancement
